#these are the necessary setup files for using the meanicinbox.py program
#this is a yaml file

#latfile and lonfile describe lats and lons of the 25km grid that is used for the
#data
#These files can be found
#here: https://nsidc.org/data/polar-stereo/tools_geo_pixel.html
latfile: /home/akutan/strausz/noaa_pmel_github/EcoFOCI_ssmi_ice/psn25lats_v3.dat
lonfile: /home/akutan/strausz/noaa_pmel_github/EcoFOCI_ssmi_ice/psn25lons_v3.dat
latlon_nc: NSIDC0771_LatLon_PS_N25km_v1.0.nc

#this is directory where you keep your bootstrap data, must have sub directories
#for each year of data
bootstrap: /home/disk3/projects/ecofoci/foci_lfstore/data_sets/ssmi_ice/bootstrap/ 
#this is the directory for NASA's nrt data.  It is not broken down into years.  
#it is only used when bootstrap data is not yet available
nrt: /home/disk3/projects/ecofoci/foci_lfstore/data_sets/ssmi_ice/nrt/
#year for which latest bootstrap data is available, will need to be changed as
#new data is released
boot_year: 2023


